resources:
  - name: helm_gitRepo_demo
    type: GitRepo
    configuration:
      path: shanilevy/kubernetes_example
      gitProvider: GitHub-Shani
  - name: helmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: app_helm_chart
      buildNumber: 1
  - name: helmPromotedAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: app_helm_chart
      buildNumber: 1
  - name: getDockerLatest
    type: Aql
    configuration:
      sourceArtifactory: ArtifactoryHA
      query: 'items.find ({"repo":"docker-prod-local","type":"folder","$and":[{"path":{"$match":"docker-multi-app*"}},{"path":{"$nmatch":"jfrog-docker-app/latest"}}]}).include("path","created","name","repo").sort({"$desc" : ["created"]}).limit(1)'
pipelines:
  - name: helm_chart_pipeline
    steps:
      - name: helm_demo
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: docker.artifactory-cluster.soleng-us.team/jfrog-docker-app
            dockerImageTag: ${run_number}
          inputResources:
            - name: helm_gitRepo_demo
            - name: getDockerLatest
          integrations:
            - name: ArtifactoryHA
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_ArtifactoryHA_url --user $int_ArtifactoryHA_user --apikey $int_ArtifactoryHA_apikey --interactive=false
            - pushd $res_helm_gitRepo_demo_resourcePath
            - echo $int_ArtifactoryHA_url
            - echo $run_Number
            - add_run_variable repo="helm"
            - add_run_variable image_tag="docker.artifactory-cluster.soleng-us.team/jfrog-docker-app:latest"
            - add_run_variable buildStepName=${step_name}
            - add_run_variable ${step_name}_buildNumber=${run_number}
            - add_run_variable ${step_name}_buildName=${pipeline_name}
            - sed -i 's/0.1.1/0.1.$run_number/' create-docker-multi-app-helm-chart/helm/docker-multi-app-chart/Chart.yaml
            - helm init --client-only
            - sed -i 's/latest/${image_tag}/g' $res_helm_gitRepo_demo_resourcePath/docker-multi-app-chart/values.yaml
            - sh "helm package ./docker-multi-app-chart/"
            - jfrog rt u '*.$run_number.tgz' ${repo} --build-name=$pipeline_name --build-number=$run_number --props='release-bundle=true'
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt dl docker-prod-local/docker-multi-app/${image_tag}/manifest.json --build-name=$pipeline_name --build-number=$run_number
            - jfrog rt bp $pipeline_name $run_number
            - save_run_state /tmp/jfrog/. jfrog
