resources:
  - name: k8s_gitRepo_demo
    type: GitRepo
    configuration:
      path: shanilevy/kubernetes_example
      gitProvider: GitHub-Shani
  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: gradleBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: NpmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
  - name: NpmBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
  - name: frameworkGenericFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: ArtifactoryHA
      pattern: tomcat-local/(*).tar.gz
      target: './{1}.tar.gz'
      flat: true
  - name: dockerFrameworkBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-3-base_image
      buildNumber: 1
  - name: javaAppFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: ArtifactoryHA
      pattern: gradle-release-local/org/jfrog/example/gradle/webservice/1.1.2/*.war
      target: war/webservice.war
      flat: true
  - name: dockerFrameworkBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-3-base_image
      buildNumber: 1
  - name: dockerApplBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-4-app_image
      buildNumber: 1
  - name: dockerApplBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-4-app_image
      buildNumber: 1
  - name: getDockerAppImage
    type: Aql
    configuration:
      sourceArtifactory: ArtifactoryHA
      query: 'items.find ({"repo":"docker-prod-local","type":"folder","$and":[{"path":{"$match":"docker-multi-app*"}},{"path":{"$nmatch":"jfrog-docker-app/latest"}}]}).include("path","created","name","repo").sort({"$desc" : ["created"]}).limit(1)'
  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceArtifactory: ArtifactoryHA
      name: demo-app
      version: v1.0.0
  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceArtifactory: ArtifactoryHA
      name: demo-app
      version: v1.0.0
  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceArtifactory: ArtifactoryHA
      serviceName: "Edge*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"
pipelines:
  - name: demo_seven_steps_pipeline
    steps:
      - name: step1_pipeline_buildWithGradle
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-example
          configFileLocation: .
          configFileName: gradle-art-config
          forceXrayScan: false
          autoPublishBuildInfo: true
          inputResources:
            - name: k8s_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: ArtifactoryHA
      - name: promoteJavaBuild
        type: PromoteBuild
        configuration:
          targetRepository: gradle-release-local
          includeDependencies: false
          inputResources:
            - name: gradleBuildInfo
          outputResources:
            - name: gradleBuildInfoPromoted
      - name: step2_pipeline_buildUIWithNpm
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: create-ui-package
          repositoryName: npm
          inputResources:
            - name: k8s_gitRepo_demo
          integrations:
            - name: ArtifactoryHA
      - name: publishNpmBuild
        type: NpmPublish
        configuration:
          repositoryName: npm-dev-local
          inputSteps:
            - name: step2_pipeline_buildUIWithNpm
          integrations:
            - name: ArtifactoryHA
      - name: publishNpmBuildInfo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publishNpmBuild
          #integrations:
           # - name: ArtifactoryHA
          outputResources:
            - name: NpmBuildInfo
      - name: promoteNpmBuild
        type: PromoteBuild
        configuration:
          targetRepository: npm-release-local
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: NpmBuildInfo
          outputResources:
            - name: NpmBuildInfoPromoted
      - name: step3_pipeline_buildDockerFramework
        type: DockerBuild
        configuration:
          affinityGroup: fmkGroup
          dockerFileLocation: docker-framework/
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory-cluster.soleng-us.jfrog.team/jfrog-docker-framework
          dockerImageTag: $run_number
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: k8s_gitRepo_demo
            - name: frameworkGenericFileSpec
        execution:
          onStart:
            - echo "Preparing for work"
            - >-
              sed -ie 's#docker.artifactory/##g'
              $res_k8s_gitRepo_demo_resourcePath/docker-framework/Dockerfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "You Lose"
          onComplete:
            - echo "Leave it as you found it. Let's clean it"
      - name: pushDockerFramework
        type: DockerPush
        configuration:
          affinityGroup: fmkGroup
          targetRepository: docker-dev-local
          forceXrayScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: ArtifactoryHA
          inputSteps:
            - name: step3_pipeline_buildDockerFramework
          outputResources:
            - name: dockerFrameworkBuildInfo
      - name: promoteFrameworkBuild
        type: PromoteBuild
        configuration:
          affinityGroup: fmkGroup
          targetRepository: docker-prod-local
          inputResources:
            - name: dockerFrameworkBuildInfo
          outputResources:
            - name: dockerFrameworkBuildInfoPromoted
      - name: step4_pipeline_buildDockerApp
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: docker-app/
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory-cluster.soleng-us.jfrog.team/jfrog-docker-app
          dockerImageTag: $run_number
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: k8s_gitRepo_demo
            - name: javaAppFileSpec
            - name: dockerFrameworkBuildInfoPromoted
            - name: NpmBuildInfoPromoted
            - name: gradleBuildInfoPromoted
          inputSteps:
            - name: promoteFrameworkBuild
            - name: promoteJavaBuild
            - name: promoteNpmBuild
        execution:
          onStart:
            - echo "Preparing for work"
            - curl $int_ArtifactoryHA_url/api/system/ping
            - >-
              sed -ie
              's#docker.artifactory/#docker.artifactory-cluster.soleng-us.jfrog.team/#g'
              $res_k8s_gitRepo_demo_resourcePath/docker-app/Dockerfile
            - >-
              sed -ie
              's#docker-framework:latest#jfrog-docker-framework:'"$res_dockerFrameworkBuildInfoPromoted_buildNumber"'#g'
              $res_k8s_gitRepo_demo_resourcePath/docker-app/Dockerfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "You Lose"
          onComplete:
            - echo "Leave it as you found it. Let's clean it"
      - name: pushDockerApp
        type: DockerPush
        configuration:
          affinityGroup: bldGroup
          targetRepository: docker-dev-local
          forceXrayScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: ArtifactoryHA
          inputSteps:
            - name: step4_pipeline_buildDockerApp
          outputResources:
            - name: dockerApplBuildInfo
      - name: promoteAppBuild
        type: PromoteBuild
        configuration:
          affinityGroup: bldGroup
          targetRepository: docker-prod-local
          inputResources:
            - name: dockerApplBuildInfo
          outputResources:
            - name: dockerApplBuildInfoPromoted
            
  - name: demo_release_pipeline
    steps:
        - name: bundle
          type: CreateReleaseBundle
          configuration:
            releaseBundleName: demo-app
            releaseBundleVersion: v1.0.$run_number
            dryRun: false
            sign: false
            description: "some random test description"
            inputResources:
              - name: dockerApplBuildInfoPromoted
              - name: getDockerAppImage
                trigger: false
            outputResources:
              - name: releaseBundle_demo

        - name: sign_demo
          type: SignReleaseBundle
          configuration:
            inputResources:
              - name: releaseBundle_demo
            outputResources:
              - name: signedBundle_demo

        - name: distribute
          type: DistributeReleaseBundle
          configuration:
            dryRun: false
            inputResources:
              - name: signedBundle_demo
              - name: distributionRules_demo
