resources:
  - name: k8s_gitRepo_demo
    type: GitRepo
    configuration:
      path: shanilevy/kubernetes_example
      gitProvider: GitHub-Shani
  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: gradleBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: NpmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
  - name: NpmBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
pipelines:
  - name: demo_seven_steps_pipeline
    steps:
      - name: step1_pipeline_buildWithGradle
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-example
          configFileLocation: .
          configFileName: gradle-art-config
          forceXrayScan: false
          autoPublishBuildInfo: true
          inputResources:
            - name: k8s_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: ArtifactoryHA
      - name: promoteJavaBuild
        type: PromoteBuild
        configuration:
          targetRepository: gradle-release-local
          includeDependencies: false
          inputResources:
            - name: gradleBuildInfo
          outputResources:
            - name: gradleBuildInfoPromoted
      - name: step2_pipeline_buildUIWithNpm
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: create-ui-package
          repositoryName: npm
          inputResources:
            - name: k8s_gitRepo_demo
          integrations:
            - name: ArtifactoryHA
      - name: publish_ui_pkg
        type: NpmPublish
        configuration:
          repositoryName: npm
          inputSteps:
            - name: step2_pipeline_buildUIWithNpm
          integrations:
            - name: ArtifactoryHA
          outputResources:	
            - name: NpmBuildInfo
        execution:
          onStart:
            - export inputNpmBuildStepName="step2_pipeline_buildUIWithNpm"
      - name: publish_ui_pkg_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_ui_pkg
          #integrations:
           # - name: Art1
          outputResources:
            - name: NpmBuildInfo
