resources:
  - name: k8s_gitRepo_demo
    type: GitRepo
    configuration:
      path: shanilevy/kubernetes_example
      gitProvider: GitHub-Shani
  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: gradleBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-1-java
      buildNumber: 1
  - name: NpmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
  - name: NpmBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-2-npm
      buildNumber: 1
  - name: frameworkGenericFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: ArtifactoryHA
      pattern: tomcat-local/(*).tar.gz
      target: './{1}.tar.gz'
      flat: true
- name: dockerFrameworkBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-3-base_image
      buildNumber: 1
  - name: javaAppFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: ArtifactoryHA
      pattern: gradle-release-local/org/jfrog/example/gradle/webservice/1.1.2/*.war
      target: war/webservice.war
      flat: true
  - name: dockerFrameworkBuildInfoPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: pipeline-step-3-base_image
      buildNumber: 1
pipelines:
  - name: demo_seven_steps_pipeline
    steps:
      - name: step1_pipeline_buildWithGradle
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-example
          configFileLocation: .
          configFileName: gradle-art-config
          forceXrayScan: false
          autoPublishBuildInfo: true
          inputResources:
            - name: k8s_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: ArtifactoryHA
      - name: promoteJavaBuild
        type: PromoteBuild
        configuration:
          targetRepository: gradle-release-local
          includeDependencies: false
          inputResources:
            - name: gradleBuildInfo
          outputResources:
            - name: gradleBuildInfoPromoted
      - name: step2_pipeline_buildUIWithNpm
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: create-ui-package
          repositoryName: npm
          inputResources:
            - name: k8s_gitRepo_demo
          integrations:
            - name: ArtifactoryHA
      - name: publish_ui_pkg
        type: NpmPublish
        configuration:
          repositoryName: npm-dev-local
          inputSteps:
            - name: step2_pipeline_buildUIWithNpm
          integrations:
            - name: ArtifactoryHA
      - name: publish_ui_pkg_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_ui_pkg
          #integrations:
           # - name: ArtifactoryHA
          outputResources:
            - name: NpmBuildInfo
      - name: promote_ui_build
        type: PromoteBuild
        configuration:
          targetRepository: npm-release-local
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: NpmBuildInfo
          outputResources:
            - name: NpmBuildInfoPromoted
      - name: step3_pipeline_buildDockerFramework
        type: DockerBuild
        configuration:
          affinityGroup: fmkGroup
          dockerFileLocation: docker-framework/
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory-cluster.soleng-us.jfrog.team/jfrog-docker-framework
          dockerImageTag: $run_number
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: k8s_gitRepo_demo
            - name: frameworkGenericFileSpec
        execution:
          onStart:
            - echo "Preparing for work"
            - >-
              sed -ie 's#docker.artifactory/##g'
              $res_srcRepository_resourcePath/docker-framework/Dockerfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "You Lose"
          onComplete:
            - echo "Leave it as you found it. Let's clean it"
      - name: pushDockerFramework
        type: DockerPush
        configuration:
          affinityGroup: fmkGroup
          targetRepository: docker-dev-local
          forceXrayScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: ArtifactoryHA
          inputSteps:
            - name: step3_pipeline_buildDockerFramework
          outputResources:
            - name: dockerFrameworkBuildInfo
      - name: promoteFrameworkBuild
        type: PromoteBuild
        configuration:
          affinityGroup: fmkGroup
          targetRepository: docker-prod-local
          inputResources:
            - name: dockerFrameworkBuildInfo
          outputResources:
            - name: dockerFrameworkBuildInfoPromoted
